package badsmells;

/*
 Smell: Divergent Change

 ORIGINAL PROBLEM:
 One class mixed three unrelated concerns: report formatting, SQL generation,
 and CSV export. Each concern has a different reason to change (e.g., the
 report footer changes for branding, the table name changes for DB migration,
 the CSV separator changes for a new spreadsheet tool), so they were
 incorrectly forced into one class.

 REFACTORINGS APPLIED:
 1. Extract Class, ExamReportFormatter, ExamSqlBuilder, ExamCsvExporter.
 2. Move Method and field, each concern takes its own fields and methods.

 WHY BETTER:
 Each class now has exactly one reason to change. A DB schema rename touches
 only ExamSqlBuilder; a new report layout touches only ExamReportFormatter.
 The classes are smaller, easier to test in isolation, and easier to reuse.
 */
public class DivergentChangeExample {

    static class ExamReportFormatter {
        private final String title  = "Exam Results";
        private final String footer = "Generated by registrar office";

        public String format(String name, int score) {
            return title + "\n" + name + ": " + score + "\n" + footer;
        }
    }

    static class ExamSqlBuilder {
        private final String tableName   = "exam_results";
        private final String databaseUrl = "jdbc:mysql://localhost:3306/school";

        public String buildInsert(String name, int score) {
            return "/* " + databaseUrl + " */ INSERT INTO " + tableName
                + "(name, score) VALUES ('" + name + "', " + score + ")";
        }
    }

    static class ExamCsvExporter {
        private final String  separator          = ",";
        private final boolean includeHeader      = true;

        public String export(String name, int score) {
            String row = name + separator + score;
            return includeHeader ? "name" + separator + "score\n" + row : row;
        }
    }

    public void clientCode() {
        ExamReportFormatter formatter = new ExamReportFormatter();
        ExamSqlBuilder      builder   = new ExamSqlBuilder();
        ExamCsvExporter     exporter  = new ExamCsvExporter();

        System.out.println(formatter.format("Nino", 95));
        System.out.println(builder.buildInsert("Nino", 95));
        System.out.println(exporter.export("Nino", 95));
    }
}
